### ISSUE TITLE
Alpha ESC Telemetry Code Inquiry

### ISSUE THREAD

**Issue by djamal27** [PR-DC/PRDC_TMAESC#1]
I came across your telemetry arduino code that interfaces with the T-motor Alpha ESC. I have a basic understanding of programming and Arduino, so I apologize for these low level questions. I wanted to ask if this program allows for the programming of the ESC? If so could you provide some guidance for the pinouts for the ESC as well as any modification that needs to be made to the code.

Your time and effort is greatly appreciated. Thanks in advance.

**Comment by v-petrovic** [comment]
Hi, the code doesn't have an option of ESC programming. Programming protocol has not been made public by the manufacturer.
